package com.matheus.srv_portfolio_scheduler.application.ports.input.commands;

import com.matheus.srv_portfolio_scheduler.application.command.CreateRecommendedPortfolio.CreateRecommendedPortfolioCommand;
import com.matheus.srv_portfolio_scheduler.application.command.CreateRecommendedPortfolio.CreateRecommendedPortfolioResponse;

public interface CreateRecommendedPortfolioUseCase {
    CreateRecommendedPortfolioResponse handler(CreateRecommendedPortfolioCommand request);
}
